<?php defined('BASEPATH') OR exit('No direct script access allowed.');

function getTableSettings() {
  return array(
    "page_title"          => "",
    "primary_table"       => "process_details",
    "default_column"      => "process_details.id",
    "table"               => array("process_details","processes"),
    "join_conditions"        => array('process_details.process_id=processes.id'),
    "join_type"           => "",
    "where"               => "",
    "where_ids"           => "",
    "order_by"            => "",
    "limit"               => "20",
    "extra_select_column" => "process_details.id",
    "actionFunction"      => "",
    "headingFunction"     => "list_settings",
    "search_url"          => "process_fields",
    "add_title"           => "",
    "export_title"        => "",
    "edit"                => "",
    'clear_filter'        => true
  );
}

function get_row_id($melting_lot_id, $department_name) {
  return strtolower(str_replace(' ', '_', $melting_lot_id.' '.str_replace('+', '_', $department_name)));
}
  
function list_settings() {
  return array(
    array("Lot No", "lot_no", false, "lot_no", false, TRUE,'processes.lot_no as lot_no'),
    array("Date", "created_at", false, "created_at", false, TRUE,'processes.created_at as created_at'),
    array("Product name", "product_name", false, "product_name", TRUE, TRUE,'processes.product_name as product_name'),
    array("Process name", "process_name", false, "process_name", TRUE, TRUE,'processes.process_name as process_name'),
    array("Department name", "department_name", false, "department_name", TRUE, TRUE,'processes.department_name as department_name'),
    // array("", "action", FALSE, "action", FALSE, FALSE),
  );
}



/*
  | [0] => Label
  | [1] => Placeholder  
  | [2] => Mandatory/Not Mandatory
  | [3] => Class
  | [4] => Autofocus
  | [5] => Readonly
  | [6] => disabled
*/

function get_field_attribute($table, $field) {
  $attributes['process_fields'] = array(
    'id'            => array('', '', TRUE, '', TRUE),
    'worker' => array('', 'worker', false, '', TRUE),
    "out_weight"   => array("Out Weight", "", FALSE, "", TRUE),
    'tanishq_out'  => array('Tanishq Out', '', FALSE, '', TRUE),
    "bounch_out"   => array("Bounch Out", "", FALSE, "", TRUE),
    "category_name"   => array("Category name", "", FALSE, "", TRUE),
    "design_name"   => array("Design name", "", FALSE, "", TRUE),
    "market_design_name"   => array("Market design name", "", FALSE, "", TRUE),
    "gauge"   => array("Gauge", "", FALSE, "", TRUE),
    "balance"   => array("Balance", "", FALSE, "", TRUE),
    "line"   => array("Line", "", FALSE, "", TRUE),
    "process_id"   => array("", "", FALSE, "", TRUE),
    'process_id'  => array('', '', TRUE, '', TRUE),
    'field_name'  => array('', '', TRUE, '', TRUE),
    'total_qty'  => array('Total Qty', '', FALSE, '', FALSE),
    'process_factory_order_detail'  => array('', '', TRUE, '', TRUE),
    // 'process_factory_order_hook'  => array('', '', TRUE, '', TRUE),
    // 'process_factory_order_gpc'  => array('', '', TRUE, '', TRUE),
    'weight'  => array('', '', FALSE, '', TRUE),
    'length'  => array('', '', FALSE, '', TRUE),
    'no_of_bunch'  => array('', '', FALSE, '', TRUE),
    'design_code'  => array('', '', FALSE, '', TRUE),
    'machine_size'  => array('', '', FALSE, '', TRUE),
    'gpc_out'  => array('GPC out', '', FALSE, '', TRUE),
    'karigar'  => array('Karigar Name', '', FALSE, '', TRUE),
    'remark'  => array('', '', FALSE, '', TRUE),
    'product_name' => array('Product Name', '', FALSE, '', TRUE),
    'process_name' => array('Product Name', '', FALSE, '', TRUE),
    'lot_no' => array('Lot No', '', FALSE, '', TRUE),
    'lopster_no' => array('Lopster No', '', FALSE, '', TRUE),
    'lock_no' => array('Lock No', '', FALSE, '', TRUE),
    'department_name'  => array('Department Name', '', FALSE, '', TRUE),
    'process_sequence'  => array('', '', FALSE, '', TRUE),
    'melting_lot_id'  => array('Melting Lot ID', '', FALSE , '', TRUE),
    'lot_no'  => array('Lot No', '', FALSE, '', TRUE),
    'in_lot_purity'  => array('Lot Purity', '', FALSE, '', TRUE),
    'in_weight'  => array('IN Weight', '', FALSE, '', TRUE),
    'in_purity'  => array('IN Purity', '', FALSE, '', TRUE),
    'gold_purity'  => array('Gold Purity', '', FALSE, '', TRUE),
    'fe_in'  => array(' FE IN', '', FALSE, '', TRUE),
    'fe_out'  => array('FE OUT', '', FALSE, '', TRUE),
    'hook_in' => array('Hook In', '', FALSE, '', FALSE),
    'hook_out' => array('Hook Out', '', FALSE, '', FALSE),
    'sisma_in' => array('sisma In', '', FALSE, '', FALSE),
    'sisma_out' => array('sisma Out', '', FALSE, '', FALSE),
    'in_rod' => array('In Rod', '', FALSE, '', FALSE),
    'melting_wastage'  => array('Wastage', '', FALSE, '', TRUE),
    'wastage_gross'  => array('Wastage Purity', '', FALSE, '', TRUE),
    'wastage_fe'  => array('Wastage FE', '', FALSE, '', TRUE),
    'wastage_au_fe'  => array('Wastage AU+Fe', '', FALSE, '', TRUE),
    'next_department_karigar'  => array('Next Department Karigar', '', FALSE, '', TRUE),
    'factory_order_weight'  => array('Total Weight', '', FALSE, '', TRUE),
    'daily_drawer_in_weight'  => array('Daily drawer in weight', '', FALSE, '', TRUE),
    'next_department_karigar'  => array('Next Department Karigar', '', FALSE, '', TRUE),
    'tounch_in'  => array('Tounch', '', FALSE, '', TRUE),
    "fire_tounch_in" => array("Fire Tounch In", "", FALSE, "", TRUE),
    'tounch_no'  => array('Tounch No', '', FALSE, '', TRUE),
    'ghiss'  => array('Ghiss', '', FALSE, '', TRUE),
    'hcl_ghiss'  => array('HCL Ghiss', '', FALSE, '', TRUE),
    'loss'  => array('Loss', '', FALSE, '', TRUE),
    'loss_gross'  => array('Loss Purity', '', FALSE, '', TRUE),
    'loss_fine'  => array('Loss Fine', '', FALSE, '', TRUE),
    'au_out'  => array('AU Out', '', FALSE, '', TRUE),
    'au_out_fine'  => array('AU Out Fine', '', FALSE, '', TRUE),
    'gold'  => array('Gold', '', FALSE, '', TRUE),
    'iron'  => array('Iron', '', FALSE, '', TRUE),
    'total'  => array('Total', '', FALSE, '', TRUE),
    'out_weight'  => array('Out Weight', '', FALSE, '', TRUE),
    'out_purity'  => array('Out Purity', '', FALSE, '', TRUE),
    'micro_coating'  => array('Micro Coating', '', FALSE, '', TRUE),
    'balance'  => array('Balance', '', FALSE, '', TRUE),
    'balance_gross'  => array('Balance Gross', '', FALSE, '', TRUE),
    'balance_fine'  => array('Balance Fine', '', FALSE, '', TRUE),
    'daily_drawer_wastage'  => array('Daily Drawer Wastage', '', FALSE, '', TRUE),
    'cz_wastage'  => array('CZ Wastage', '', FALSE, '', TRUE),
    'hcl_wastage'  => array('HCL Wastage', '', FALSE, '', TRUE),
    'created_at'  => array('Date', '', FALSE, '', TRUE),
    'description'  => array('Description', '', FALSE, '', TRUE),
    'quantity'  => array('Quantity', '', FALSE, '', TRUE),
    'rnd_process'  => array('RND Process', '', FALSE, '', TRUE),
    'daily_drawer_type' => array('Type', 'Select', FALSE, '', TRUE),
    'pending_ghiss'  => array('Pending Ghiss', '', FALSE, '', TRUE),
    'pending_loss'  => array('Pending Loss', '', FALSE, '', TRUE),
    'design_code_type'  => array('Design Code Type', '', FALSE, '', TRUE),
    'next_department_name' => array('', '', false, '', TRUE),
    'meena_quantity'  => array('Meena Quantity', '', FALSE, '', TRUE),
    'customer_out'  => array('Customer Out', '', FALSE, '', TRUE),
    'bounch_out'  => array('Bounch Out', '', FALSE, '', TRUE),
    'customer_name'  => array('Customer Name', '', FALSE, '', TRUE),
    'srno'  => array('Uniqe code', '', FALSE, '', TRUE),
    'next_department_name'  => array('Hold Process', '', FALSE, '', TRUE),
    'factory_out'  => array('Factory Out', '', FALSE, '', TRUE),
    'order_detail_id'  => array('Order Detail', '', FALSE, '', TRUE),
    'design_code_category'  => array('Category', '', FALSE, '', TRUE),
    'max_hcl_loss'  => array('Max HCL Loss', '', FALSE, '', TRUE),
    'min_hcl_loss'  => array('Min HCL Loss', '', FALSE, '', TRUE),
    'melting_lot_category_one' => array('Category One', '', FALSE, '', TRUE),
    'melting_lot_category_two' => array('Category Two', '', FALSE, '', TRUE),
    'melting_lot_category_three' => array('Category Two', '', FALSE, '', TRUE),
    'concept' => array('Concept', '', FALSE, '', TRUE),
    'recutting_out' => array('Recutting Out', '', FALSE, '', TRUE),
    'tone' => array('Tone', '', FALSE, '', TRUE),
    'gemstone_in' => array('Gemstone In', '', FALSE, '', TRUE),
    'gemstone_out' => array('Gemstone Out', '', FALSE, '', TRUE),
    'karigar_loss' => array("KArigar Loss", "", FALSE, "", TRUE),
    'request_uri' => array("Request URI", "", FALSE, "", TRUE),
    'stone_vatav' => array("Stone Vatav", "", FALSE, "", TRUE),
    'out_stone_vatav' => array("Out Stone Vatav", "", FALSE, "", TRUE),
    "order_id"   => array("", "", FALSE, "", TRUE),
    "parent_id"   => array("", "", FALSE, "", TRUE),
    "stone_in"   => array("", "", FALSE, "", TRUE),
    "rejected"   => array("", "", FALSE, "", TRUE),
    "rejected_out"   => array("", "", FALSE, "", TRUE),
    "rejected_qty"   => array("", "", FALSE, "", TRUE),
    "gpc_out_qty"   => array("", "", FALSE, "", TRUE),
    "out_quantity"   => array("", "", FALSE, "", TRUE),
    "job_card_no"   => array("", "", FALSE, "", TRUE),

    "stone_out"   => array("", "", FALSE, "", TRUE),
    "stone_count"   => array("", "", FALSE, "", TRUE),
    "spring_in"   => array("", "", FALSE, "", TRUE),
    "spring_out"   => array("", "", FALSE, "", TRUE),
    "city"   => array("", "", FALSE, "", TRUE),
    "city"   => array("", "", FALSE, "", TRUE),
    "accept_packing_list"   => array("", "", FALSE, "", TRUE),
    "rejected"   => array("", "", FALSE, "", TRUE),
  );
    $attributes["process_factory_order_details"] =$attributes["factory_order_details"]=$attributes["bunch_order_details"]= array(
      "id" => array("", "", FALSE, "", FALSE),
      "order_ids" => array("", "", FALSE, "", FALSE),
      "process_id"  => array("", "", FALSE, "", TRUE),
      "out_weight"   => array("Out Weight", "", FALSE, "", TRUE),
      "factory_order_detail_id"   => array("", "", FALSE, "", TRUE),
       "id" => array("", "", FALSE, "", FALSE),
       "total_qty" => array("", "", FALSE, "", FALSE),
      "customer_out"   => array("", "", FALSE, "", TRUE),
      "wt_in_18_inch"   => array("", "", FALSE, "", TRUE),
      "wt_in_24_inch"   => array("", "", FALSE, "", TRUE),
      "wt_per_inch"   => array("", "", FALSE, "", TRUE),
      "due_date"   => array("", "", FALSE, "", TRUE),
      'customer_name' => array('', '', true, '', FALSE),
      'ka_chain_factory_order_id'=> array('', '', true, '', FALSE),
      '14_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '15_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '16_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '18_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '20_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '22_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '24_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '26_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '28_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '30_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '32_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '34_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '36_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '14_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '15_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '16_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '18_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '20_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '22_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '24_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '26_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '28_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '30_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '32_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '34_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '36_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '14_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '15_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '16_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '18_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '20_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '22_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '24_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '26_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '28_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '30_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '32_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '34_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '36_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '14_inch_qty'     => array('', '', TRUE, '', TRUE),
      '15_inch_qty'     => array('', '', TRUE, '', TRUE),
      '16_inch_qty'     => array('', '', TRUE, '', TRUE),
      '18_inch_qty'     => array('', '', TRUE, '', TRUE),
      '20_inch_qty'     => array('', '', TRUE, '', TRUE),
      '22_inch_qty'     => array('', '', TRUE, '', TRUE),
      '24_inch_qty'     => array('', '', TRUE, '', TRUE),
      '26_inch_qty'     => array('', '', TRUE, '', TRUE),
      '28_inch_qty'     => array('', '', TRUE, '', TRUE),
      '30_inch_qty'     => array('', '', TRUE, '', TRUE),
      '32_inch_qty'     => array('', '', TRUE, '', TRUE),
      '34_inch_qty'     => array('', '', TRUE, '', TRUE),
      '36_inch_qty'     => array('', '', TRUE, '', TRUE),

      '17_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '19_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '21_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '23_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '25_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '27_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '29_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '31_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '33_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '35_inch_qty_ready'     => array('', '', TRUE, '', TRUE),
      '17_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '19_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '21_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '23_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '25_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '27_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '29_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '31_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '33_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '35_inch_qty_pending'     => array('', '', TRUE, '', TRUE),
      '17_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '19_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '21_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '23_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '25_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '27_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '29_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '31_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '33_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '35_inch_qty_in'     => array('', '', TRUE, '', TRUE),
      '17_inch_qty'     => array('', '', TRUE, '', TRUE),
      '19_inch_qty'     => array('', '', TRUE, '', TRUE),
      '21_inch_qty'     => array('', '', TRUE, '', TRUE),
      '23_inch_qty'     => array('', '', TRUE, '', TRUE),
      '25_inch_qty'     => array('', '', TRUE, '', TRUE),
      '27_inch_qty'     => array('', '', TRUE, '', TRUE),
      '29_inch_qty'     => array('', '', TRUE, '', TRUE),
      '31_inch_qty'     => array('', '', TRUE, '', TRUE),
      '33_inch_qty'     => array('', '', TRUE, '', TRUE),
      '35_inch_qty'     => array('', '', TRUE, '', TRUE),
    );

    $attributes["process_bunch_order_details"] = array(
      "id" => array("", "", FALSE, "", FALSE),
      "process_id"  => array("", "", FALSE, "", TRUE),
      "bounch_out"   => array("Bunch Out", "", FALSE, "", TRUE),
      "bunch_order_detail_id"   => array("", "", FALSE, "", TRUE),
       "id" => array("", "", FALSE, "", FALSE),
      "customer_out"   => array("", "", FALSE, "", TRUE),
      "wt_in_18_inch"   => array("", "", FALSE, "", TRUE),
      "wt_in_24_inch"   => array("", "", FALSE, "", TRUE),
      "wt_per_inch"   => array("", "", FALSE, "", TRUE),
      "due_date"   => array("", "", FALSE, "", TRUE),
      'customer_name' => array('', '', true, '', FALSE),
      'ka_chain_factory_order_id'=> array('', '', true, '', FALSE),
      'bunch_length'=> array('', '', true, '', FALSE),
      'bunch_weight'=> array('', '', true, '', FALSE),
       
    );
  return $attributes[$table][$field];
}
