<?php

require_once APPPATH . "modules/core_users/models/Core_user_role_model.php";
class User_role_model extends Core_user_role_model {
  public function __construct($data=array()) {
    parent::__construct($data);
  }

  public function get_controller_list($module_name='') {
    $modules = array();
    
    $modules['AR Gold'] = array(
      'rope_chain' =>     array('rope_chains/dashboards',
                               'rope_chains/melting_processes',
                               'rope_chains/machine_processes',
                               'rope_chains/final_processes',
                              ),
        'choco_chain' => array('choco_chains/dashboards',
                              // 'choco_chains/melting_processes',
                              // 'choco_chains/chain_making_processes',
                              'choco_chains/final_processes',
                // 'choco_chains/choco_chain_bom_settings',
                'choco_chains/ags',
                // 'choco_chains/combine_processes',
                'choco_chains/machine_processes',
                // 'choco_chains/final_processes',
                // 'choco_chains/hallmarking_processes',
                // 'choco_chains/rnd_processes',
                // 'choco_chains/hand_cutting_processes',
                // // 'choco_chains/casting_final_processes',
                // 'choco_chains/quality_processes',
                // 'choco_chains/casting_seventy_final_processes',
                // 'choco_chains/casting_ninety_final_processes',
                // 'choco_chains/imp_final_processes',
                // 'choco_chains/melting_lot_reports',
                // 'choco_chains/choco_chain_dye_processes',
                // 'choco_chains/choco_chain_dye_final_processes',
                // 'choco_chains/choco_chain_cutting_pipes',
                // 'choco_chains/choco_chain_hollow_pipes',
                // 'choco_chains/choco_chain_solid_pipes',
                // 'choco_chains/choco_chain_solid_wires',
                // 'choco_chains/choco_chain_hard_wires',

            ),

       'issue_departments' =>     array(
                               'issue_departments/issue_departments',
                               ),

        'office_outside' => array('office_outside/kdms',
                                'office_outside/hooks',
                                'office_outside/lobsters',
                                'office_outside/solid_pipes',
                                'office_outside/solid_wires',
                                'office_outside/hollow_pipes',
                                'office_outside/balls',
                                'office_outside/cutting_wires',
                                'office_outside/hard_wires',
                                'office_outside/final_processes',
                                'office_outside/cutting_pipes' ),
      'loss_outs' => array('loss_outs/melting_loss_out_processes','loss_outs/melting_loss_outs',),
     
  );
  
  $modules['common'] = array(
      'melting_room'      => array('departments/melting','dashboards/dashboards','processes/processes'),
      'dashboards'      => array('dashboards/dashboards','dashboards/process_dashboards','reports/process_wise_dashboards','dashboards/phase_wise_dashboards','reports/phase_wise_dashboard_reports','dashboards/department_dashboards','stock_summary_reports/stock_report_department_wise_balance','dashboards/daily_process_dashboards','reports/daily_process_reports','dashboards/arc_order_dashboards','reports/arc_order_dashboard_reports','reports/order_status_report_dashboards','reports/order_status_reports'),
     'dashboard_menu'      => array('dashboards/dashboards','dashboards/process_dashboards','reports/process_wise_dashboards','dashboards/phase_wise_dashboards','reports/phase_wise_dashboard_reports','dashboards/department_dashboards','stock_summary_reports/stock_report_department_wise_balance','dashboards/daily_process_dashboards','reports/daily_process_reports','dashboards/arc_order_dashboards','reports/arc_order_dashboard_reports','reports/order_status_report_dashboards','reports/order_status_reports'),
      'users' => array('users/users','users/user_roles','users/ip_addresses','users/accounts'),
      'pending_status' => array('processes/process_pendings'),
      'hallmark_receipt' => array('receipt_departments/hallmark_receipts','processes/process_hallmark_in'),
     'process_tounch_loss_fine' => array('processes/process_tounch_loss_fine'),
     'masters' => array('masters/accounts','masters/machine_masters',),
     'process_details' => array('processes/process_details','processes/process_fields'),
     'loss_receipts'      => array('receipt_departments/loss_receipts'),

    /* 'masters' => array('masters/category_1','masters/category_2',
                        'masters/category_3','masters/category_4',
                        'masters/category_5','masters/category_6',
                        'masters/machine_masters',
                        'masters/item_code_masters',
                        'masters/chains',
                        'masters/processes_name',
                        'masters/process_detail_fields',
                        'masters/alloy_element_details',
                        'masters/rolling_delay_time_masters',
                        'masters/wastage_masters'),*/
     
     'dd_issue_departments' => array('daily_drawers/daily_drawer_issue_departments',
                     'daily_drawers/daily_drawer_karigar_issue_departments'),

     'daily_drawers'       => array('daily_drawers/daily_drawers',
                                    'daily_drawers/daily_drawer_processes',
                                    'daily_drawers/cz_processes',
                                    'daily_drawers/daily_drawer_receipts',
                                    'daily_drawers/daily_drawer_in_out_views',
                                    'daily_drawers/daily_drawer_wastage_views',

                                    'daily_drawers/melting_processes',
                                    'daily_drawers/daily_drawer_wastages',

                                    'issue_and_receipts/daily_drawer_wastage_ledgers',
                                    'issue_and_receipts/karigar_ledgers',
                                    'issue_and_receipts/stone_ledgers',
                                    'issue_and_receipts/rod_ledgers',
                                    
                                    'daily_drawers/daily_drawer_issue_departments',
                                    'daily_drawers/daily_drawer_karigar_issue_departments',

                                    'daily_drawers/chain_wise_daily_drawer_summeries',

                                    'daily_drawers/box_weights',

                                    'daily_drawers/karigar_wise_daily_drawers',
                                    'daily_drawers/karigar_wise_fancy_chain_daily_drawers',
                                    'daily_drawers/karigar_wise_sisma_chain_daily_drawers',

                                    'daily_drawers/daily_drawer_wastage_category_reports',),
     'daily_drawer_hold'=>array('daily_drawers/daily_drawer_hold_processes'),
     

     'wastages' => array('tounch_outs/fire_tounch_reports',
                         'tounch_outs/fire_tounch_out_processes',
                         'tounch_outs/fire_tounch_out_melting_processes',

                         'tounch_outs/tounch_reports',
                         'tounch_outs/tounch_out_melting_processes',
                         'tounch_outs/tounch_out_processes',

                         'ghiss_outs/ghiss_out_processes',
                         'ghiss_outs/ghiss_out_processes',
                         'ghiss_outs/tounch_ghiss_out_processes',
                         'ghiss_outs/ghiss_out_melting_processes',
                         'ghiss_outs/ghiss_out_final_processes',

                         'melting_wastage_refine_outs/melting_wastage_refine_out_processes',
                         'melting_wastage_refine_outs/melting_wastage_refine_out_melting_processes',

                         'issue_and_receipts/ghiss_ledgers',
                         'issue_and_receipts/department_wise_ghiss_ledgers',
                         'issue_and_receipts/pending_ghiss_ledgers',

                         'ghiss_outs/ghiss_reports',
                         'pending_ghiss_outs/pending_ghiss_out_processes',
                         'pending_ghiss_outs/pending_ghiss_issue_processes',

                         'loss_outs/loss_out_processes',
                         'loss_outs/loss_out_melting_processes',
                         'loss_outs/pending_loss_outs',
                         'loss_outs/loss_reports',
                         'loss_outs/product_wise_loss_reports',
                         'loss_outs/product_wise_loss_details',
                         'loss_outs/loss_category_reports',

                         'loss_outs/loss_percentage_reports',
                         'issue_and_receipts/loss_ledgers',
                         'issue_and_receipts/overall_loss_ledgers',
                         ),
     'wastage_masters'=>array('wastages/wastage_masters'),
     'hcl' => array('hcl/hcl_wastages',
                    'hcl/hcl_processes',
                    'hcl/hcl_melting_processes',
                    'hcl/hcl_process_balance',
                    'hcl/hcl_wastage_balance',
                    'hcl/hcl_lot_wise_reports',

                    'issue_and_receipts/hcl_loss_ledgers',
                    'issue_and_receipts/rope_ghiss_ledgers',

                    'hcl_ghiss_outs/hcl_ghiss_wastages',
                    'hcl_ghiss_outs/hcl_ghiss_out_processes',
                    'hcl_ghiss_outs/hcl_ghiss_out_melting_processes',

                    // 'parent_lots/parent_lots',

                    'parent_lot_loss/parent_lot_loss',
                    'parent_lot_loss/parent_lot_loss_view',

                    'reports/hcl_reports',
                    'reports/alloy_element_detail_reports',

                    'reports/parent_lot_wise_reports',
                    'reports/karigar_report_parent_lot_wise',

                    'dashboards/hcl_dashboards'),

     'rnds' => array('rnds/rnd_receipts',
                      'rnds/rnd_issues',
                      'rnds/rnd_karigar_receipts',
                      'rnds/rnd_list',
                      'rnds/rnd_karigar_issues',
                      'rnds/rnd_karigar_reports',
                      'issue_and_receipts/rnd_ledgers'),

     
     'set_hcl_min_max_hcl_loss' => array('processes/process_max_min_hcl_losses'),
     'chains' => array('chains/chain_issues'),
     'stones' => array('stones/stone_issues',),
     'metal_issues' => array('metals/metal_issues'),
     'product_rollings' => array('stock_summary_reports/product_rollings',),
     'combine_loss_ledgers' => array('issue_and_receipts/combine_loss_ledgers'),
     'yellow_qr_codes' => array('qr_codes/yellow_qr_codes','qr_codes/yellow_qr_code_details','qr_codes/yellow_design_details'),
     'generate_lot_qr_codes' => array('qr_codes/generate_lot_qr_codes','qr_codes/generate_lot_qr_code_details'),
     'generate_lot_taggings' => array('qr_codes/generate_lot_taggings','qr_codes/generate_lot_tagging_details'),
     'catalog_qr_codes' => array('catalog_qr_codes/catalog_qr_codes','catalog_qr_codes/catalog_qr_code_details','catalog_qr_codes/catalog_design_details'),
      'processes_with_chains' => array('receipt_departments/receipt_departments',
                          'receipt_departments/chain_receipts',
                          'receipt_departments/rhodium_receipts',
                          'internals/internal_receipts',
                          'internals/internal_final_processes',
                          
                          'qr_codes/qr_codes','qr_codes/Qr_code_details','qr_codes/design_details',
                          'receipt_departments/finished_goods_receipts',
                          'alloys/alloy_receipts',
                          'alloys/alloy_issues',
                          'alloys/alloy_reports',
                          'issue_and_receipts/alloy_ledgers',
                          'issue_and_receipts/tounch_out_ledgers',
                          'melting_lots/melting_lots',
                          'melting_lots/melting_lot_details',
                          'melting_lots/sub_melting_lot_details',
                          'melting_lots/melting_lot_alloy_details',
                          'melting_lots/parent_lots',
                          'settings/alloy_details',
                          'masters/machine_masters',
                          'settings/karigars',
                          'settings/rods',
                          'settings/alloy_types',
                          'settings/workers',
                          'settings/person_productions',
                          'settings/rooms',
                          'settings/categories',
                          'settings/category_fours',
                          'report_processes/report_processes',
                          'chitties/chitties',
                          'processes/process_informations',
                          'processes/process_quators',
                          'processes/process_factory_order_details',
                          'processes/process_factory_order_hook_details',
                          'processes/process_fields',
                          'processes/process_groups',
                          'processes/process_details',
                          'processes/hook_kdm_details',
                          'processes/process_karigars',
                          'processes/process_workers',
                          'processes/process_customers',
                          'processes/process_srnos',
                          'processes/process_outsides',
                          'processes/process_hook_kdm_purities',
                          'processes/process_tounch_purities',
                          'processes/process_chain_names',
                          'processes/process_category_one',
                          'processes/process_category_two',
                          'processes/process_machine_sizes',
                          'processes/process_design_codes',
                          'processes/process_machine_no',
                          'processes/process_descriptions',
                          'processes/process_hooks',
                          'processes/processes_in_weight_details',
                          'processes/process_report_lists',
                          'stock_summary_reports/stock_report_lists',
                          'processes/process_records',
                          'processes/process_archives',
                          'processes/process_out_weights',
                          'processes/process_statuses',
                          'processes/process_departments',
                          'processes/process_compute',
                          'processes/Process_hallmark_in',
                          'processes/process_verifications',

                          'process_details/process_details',

                          'search/search',

                          'system_checks/system_checks',
                          'system_checks/system_fixes',

                          'issue_and_receipts/ledger_balance',
                          'issue_and_receipts/alloy_gpc_vodator_ledger',
                          'issue_and_receipts/loss_report_for_accounts',
                          'issue_and_receipts/internal_ledgers',
                          'issue_and_receipts/internal_wastage_ledgers',
                          // 'issue_and_receipts/arf_issue_and_receipts',
                          // 'issue_and_receipts/arc_issue_and_receipts',
                          'issue_and_receipts/stock_summery_ledgers',
                          'issue_and_receipts/tounch_loss_fine_ledgers',
                          
                          'reports/daily_stock_reports',
                          'stock_summary_reports/adjustment_reports',
                          'stock_summary_reports/overall_rolling_reports',
                          'stock_summary_reports/stock_summary_list',
                          'stock_summary_reports/melavni_list',
                          'stock_summary_reports/alloy_vadatar_list',
                          'stock_summary_reports/stock_report_department_wise_balance',
                          'stock_summary_reports/chain_making_karigar_wise_balances',
                          'stock_summary_reports/adjustment_records',
                          'stock_summary_reports/telegram',
                          'stock_summary_reports/stock_reports',

                          'lot_loss/lot_loss',
                          'lot_loss/lot_loss_view',

                          'settings/same_karigars',
                          'settings/karigar_rates',
                          'settings/loss_percentages',
                          'settings/product_wise_loss_categories',

                          'settings/chain_purities',
                          'settings/same_karigar_imports',
                          'settings/loss_categories',
                          'settings/out_weight_categories',
                          'settings/daily_drawer_wastage_categories',
                          'settings/issue_purities',
                          'settings/process_issue_purities',
                          'settings/customers',
                          'settings/monthly_targets',
                          'settings/cities',
                          'settings/accessories',
                          'settings/departments',
                          'settings/internal_wastages',
                          'lengths/lengths',
                          'lengths/length_carts',
                          'lengths/length_cart_details',
                          'settings/open_fields',
                          'issue_and_receipts/gpc_out_ledgers',

                          'refresh/dashboards',
                          'refresh/refresh',
                          'refresh/refresh_hold',
                          'refresh/refresh_departments',
                          'refresh/refresh_final_processes',
                          'qc_departments/qc_departments',
                          'users/logout',
                          'rod_cleaning/rod_cleaning_processes',
                          'rod_cleaning/rod_cleaning_melting_processes',
                          'processes/individual_processes',
                          'processes/process_json_codes',
                          'users/change_password',
                          'settings/run_sql_query',
                          'processes/process_ledgers'),
      'stock_report'=>array('settings/run_sql_query','stock_summary_reports/stock_summary_list','stock_summary_reports/stock_summary_reports','processes/process_masters'),
      'processes'=>array('processes/processes','processes/process_archives'),
      'issue_departments'=>array('issue_departments/issue_departments',
                          'issue_departments/issue_department_quators',
                          'issue_departments/gpc_powder_issues',
                          'issue_departments/finish_goods'),
      'reports' => array('dashboards/dashboards',
                         'dashboards/chain_dashboards',
                         'dashboards/daily_process_dashboards',
                         'dashboards/arc_order_dashboards',
                         'reports/arc_order_dashboard_reports',
                         'reports/phase_wise_dashboard_reports',
                         'reports/daily_process_reports',
                         'reports/machine_no_reports',
                         'dashboards/common_dashboards',
                         'dashboards/process_dashboards',
                         'dashboards/phase_wise_dashboards',
                         'dashboards/wastage_melting_dashboards',
                         'dashboards/office_outside_dashboards',
                         'dashboards/karigar_out_dashboards',
                         'reports/purity_wise_balance_reports',
                         'dashboards/karigar_balance_dashboards',
                         'dashboards/worker_balance_dashboards',
                         'dashboards/department_dashboards',
                         'reports/department_loss_reports',
                         'reports/loss_production_reports',
                         'reports/pending_balance_reports',
                         'reports/design_wise_order_reports',
                         'reports/design_wise_order_detail_reports',
                         'reports/buffing_reports',
                         'reports/rolling_reports',
                         'reports/melting_reports',
                         'reports/karigar_calculations',
                         'reports/timing_reports',
                         'reports/worker_wise_karigar_calculations',
                         'reports/rodium_reports',
                         'reports/hand_cutting_reports',
                         'reports/feling_reports',
                         'reports/out_weight_reports',
                         'reports/flatting_reports',
                         'reports/shampoo_reports',
                         'reports/hand_dull_reports',
                         'reports/walnut_reports',
                         'reports/hammering_reports',
                         'reports/karigar_ledgers',
                         'reports/gpc_out_process_reports',
                         'reports/hallmark_ledgers',
                        'reports/rod_loss_reports',
                        'weight_checks/weight_checks',

                         'reports/karigar_lists',
                         'reports/product_worker_reports',

                         'reports/department_balance',
                         'reports/machine_no_balance_reports',

                         'reports/due_reports',
                         'reports/delay_report_karigars',
                         'reports/office_days',
                          'reports/average_production_reports',
                          'reports/machine_no_production_reports',
                          'reports/stock_checks',
                          'reports/rolling_balance_reports',
                          'reports/gpc_out_city_reports',
                          'reports/packing_detail_reports',
                          'reports/person_production_charts',
                          'reports/internal_wastages',
                          'reports/daily_change_rolling_balance_reports',
                          'reports/daily_drawer_karigar_rolling_reports',
                          'reports/melting_lot_time_reports',
                          'reports/completed_melting_reports',
                          'reports/lot_reports'),

    );
 
    $modules['BACKUP ARGOLD'] = $modules['BACKUP ARF'] = $modules['BACKUP ARC'] = array('database_restore'=>array('settings/mysqldump'));
    $modules['BACKUP ARGOLD'] = $modules['BACKUP ARF'] = $modules['BACKUP ARC'] = array('database_restore'=>array('settings/mysqldump'));
    if(HOST=='BACKUP ARC') {
      $modules = array_merge($modules['ARC'], $modules[HOST]);
    } elseif(HOST=='BACKUP ARF') {
      $modules = array_merge($modules['ARF'], $modules[HOST]);
    } elseif(HOST=='BACKUP ARGOLD') {
      $modules = array_merge($modules['AR Gold'], $modules[HOST]);
    }else {
      $modules = array_merge($modules['common'], $modules[HOST]);
    } 
    return (!empty($module_name) ? $modules[$module_name] : $modules);
  }
}
