<?php

$menu_icons = array('Backup Database' => '',
'Dashboard' => 'fa-solid fa-gears icon-orange',
                    'Melting Lots'=> 'fa-solid fa-chart-column icon-orange',
                    'Chain Orders'=> '',
                    'Parent Lots'=> '',
                    'RND' => '',
                    'Export Internal' => '',
                    'Domestic Internal' => '',
                    'Product Rolling' => '',
                    'Internal' => '',
                    'Catalog QR Code' => '',
                    'Yellow QR Code' => '',
                    'Generate Lot QR Code' => '',
                    'Hallmarking Process' => '',
                    'Packing slip' => '',
                    'Arc Order' => '',
                    'Casting' => '',
                    'Arc Customer Order' => '',
                    'QR Code' => '',
                    'Melting Wastage Refine' => '',
                    'Rope Chain' => '',
                    'Choco Chain' => '',
                    'HCL' => '',
                    'Solder' => '',
                    'Metal Issue' => '',
                    'Stone Issue' => '',
                    'Office Outside' => '',
                    'Pipe And Para Processes' => '',
                    'Refresh' => '',
                    'Daily Drawers' => '',
                    'Chain Issue' => '',
                    'Tounch' => '',
                    'Fire Tounch' => '',
                    'Ghiss' => '',
                    'Ghiss Ledger' => '',
                    'Solder Wastage' => '',
                    'Pending Ghiss' => '',
                    'Loss' => '',
                    'Stone Melting Process' => '',
                    'DD Issue Department' => '',
                    'GPC Powder Issue' => '',
                    'Issue Hook' => '',
                    'Process' => '',
                    'Spring Process' => '',
                    'Tounch Report' => '',
                    'Fire Tounch Report' => '',
                    'Loss Reports' => '',
                    'Out Weight Report' => '',
                    'Receipt Department' => '',
                    'Account Master' => '',
                    'Lot Loss' => '',
                    'Issue Department' => '',
                    'Masters' => '',
                    'Reports' => '',
                    'Stock Summary Reports' => '',
                    'Stock Reports' => '',
                    'Delay Reports' => '',
                    'Settings' => '',
                    'BOM Settings' => '',
                    'Orders' => '',
                    'User Management' => '',
                    'Stock Summary Report' => '',
                    'Datewise Stock Summary' => '',
                    'Daily Drawer Summary' => '',
                    'DD Karigar Wise' => '',
                    'Department Balance' => '',
                    'Ghiss Reports' => '',
                    'Loss Report' => '',
                    'Alloy Issue' => '',
                    'ARC' => '',
                    'Finish Goods' => '',
                    'Daily Drawer Melting Process' => '',
                    'Rod Cleaning' => '',
                    'Qc Departments' => '',
                    'Packets' => '',
                    'Processes' => '',
                    'Lengths' => '',
                    'Solder' => '',
                    'Pendant 75' => '',
                    'Hand Made Chain' => '',
                    'Factory Order' => '',
                    'Wax Tree Process' => '',
                    'Arc Chain' => '',
                    );

if(HOST=='ARC'){
  $dashboards=get_arc_dashboard_side_menu_dropdown();
}else{
  $dashboards=get_dashboard_side_menu_dropdown();
}

  $main_menu =  array(
                      'Dashboard' => $dashboards,
                      // 'Processes' => array('processes/processes'=>'Processes',
                      //                       'departments/melting'=>'Melting Room',
                      //                      'processes/individual_processes'=>'Individual Process',
                      //                      'reports/pending_balance_reports'=>'Pending Balance Reports'),
                      'Reports' => array(/*'stock_summary_reports/stock_summary_list'=> 'Report Process',
                                          'stock_summary_reports/adjustment_records'=> 'Adjustment Report',
                                          'processes/process_fields' => 'Process Field Reports',
                                          
                                          'system_checks/system_checks'=>'System Checks',
                                          
                                          'reports/karigar_calculations' => 'Product Wise Karigar Calculation',
                                          'reports/worker_wise_karigar_calculations' => 'Worker Wise Karigar Calculation',
                                          'loss_outs/loss_percentage_reports' => 'Loss percentage reports',
                                          'lot_loss/lot_loss'=>'Lot Loss','alloys/alloy_reports'=>'Alloy Report',
                                          'issue_and_receipts/alloy_ledgers'=>'Alloy Ledger',
                                         */ 'parent_lot_loss/parent_lot_loss'=>'Parent Lot Loss',
                                          'reports/department_balance' => 'Department Balance',
                                          // 'reports/ka_chain_department_balance' => 'KA Chain Department Balance',
                                          // 'issue_and_receipts/internal_ledgers' => 'Internal Ledger',
                                          // 'issue_and_receipts/internal_wastage_ledgers' => 'Internal Wastage Ledger',
                                          // 'issue_and_receipts/arf_issue_and_receipts' => 'ARF Ledger',
                                          // 'issue_and_receipts/arc_issue_and_receipts' => 'ARC Ledger',
                                          // 'issue_and_receipts/stock_summery_ledgers' => 'Stock Summary Ledger',
                                          
                                          'reports/parent_lot_wise_reports'=>'Parent Lot Wise Report',
                                          'reports/karigar_report_parent_lot_wise'=>'Karigar report Lot Wise',
                                          // 'loss_outs/loss_category_reports'=>'Loss Category Report',
                                          // 'daily_drawers/daily_drawer_wastage_category_reports'=>'Dialy Drawer Wastage Category Report',
                                          // 'reports/karigar_ledgers'=>'Karigar Ledger',
                                          // 'issue_and_receipts/karigar_ledgers'=>'Karigar Ledger Report',
                                          // 'reports/out_weight_reports'=>'Out Weight Report',
                                          // 'reports/gpc_out_process_reports'=>'GPC Out Process Report',
                                          'reports/karigar_loss_reports'=>'Karigar Loss Report',
                                           // 'issue_and_receipts/stone_ledgers'=>'Stone Ledger',
                                           // 'issue_and_receipts/rod_ledgers'=>'Rod Ledger',
                                           // 'reports/rod_loss_reports'=>'Rod Loss Report',
                                           // 'issue_and_receipts/gpc_out_ledgers'=>'GPC Out Ledger',
                                           // 'issue_and_receipts/fancy_chain_ledgers'=>'Fancy Chain Ledger',
                                           // 'issue_and_receipts/fancy_chain_fancy_hold_ledgers'=>'Fancy Hold Ledger',
                                           // 'issue_and_receipts/fancy_chain_chain_making_ledgers'=>'Fancy Chain Making Ledger',
                                         //  'reports/fancy_chain_closing_reports'=>'Fancy Chain Closing Report ',
                                           // 'issue_and_receipts/fancy_out_ledgers'=>'Fancy Out Ledger',
                                           // 'issue_and_receipts/hook_process_ledgers'=>'Hook Process Ledger',
                                           // 'reports/chain_making_wastage_reports'=>'Chain Making Wastage Report',
                                           // 'reports/product_worker_reports'=>'Product Worker Report',
                                           'reports/process_remark_reports'=>'Process Remark Report',
                                           
                                           'reports/timing_reports'=>'Timing Reports',
                                           // 'reports/in_out_weight_reports'=>'Rolling Reports',
                                           'reports/average_production_reports'=>'Avg.Production Reports',
                                           'reports/machine_no_production_reports'=>'Machine Utilization',
                                           //'reports/machine_no_balance_reports'=>'Machine no. Balance Reports',
                                           // 'reports/rolling_reports'=>'Rolling Reports',
                                           'reports/lock_dispatched_reports'=>'Lock Dispatch Reports',
                                           
                                           // 'issue_and_receipts/tounch_out_ledgers'=>'Tounch Out Ledger',

                                           'rhodium_reports/pen_rhodiums'=>'Rhodium Report',
                                           'reports/loss_production_reports'=>'Loss Production Report',
                                           'reports/stone_vatav_ledgers'=>'Stone vatav Ledgers',
                                           // 'reports/order_status_reports'=>'Order Status Reports',
                                           // 'reports/purity_wise_balance_reports'=>'Purity Wise Balance Reports',
                                           // 'reports/rolling_balance_reports'=>'Rolling Balance Reports',
                                           // 'reports/gpc_out_city_reports'=>'GPC out city Reports',
                                           // 'reports/alloy_element_detail_reports'=>'Alloy Element Detail Reports',
                                          // 'reports/packing_detail_reports'=>'ARC Stock Reports',
                                          'reports/person_production_charts'=>'Person Production Charts',
                                          // 'reports/internal_wastages'=>'Internal Wastage',
                                          'reports/trial_balance_reports'=>'Trial Balance Reports',

                                          // 'reports/daily_change_rolling_balance_reports'=>"Daily Change Rolling Balance Reports",
                                          'reports/gpc_out_reports'=>"GPC Out Reports",
                                          'reports/rejected_quantity_reports'=>"Rejected Quantity Reports",
                                          'reports/huid_quantity_reports'=>"HUID Quantity Reports",
                                          'reports/balance_quantity_reports'=>"Balance Quantity Reports",
                                          'reports/customer_order_out_weight_reports'=>'Customer Order Out Weight Reports',
                                          // 'reports/hallmark_ledgers' => 'Hallmark Ledger',
                                          'reports/melting_lot_time_reports' => 'In Melting Process Report',
                                          // 'reports/design_wise_order_reports' => 'Design Wise Order Report',
                                         // 'reports/Machine No Reports' => 'Design Wise Order Report',
                                          
                                          ),
                      /*'Stock Reports' => array(
                                               'reports/lot_reports'=>'Process Reports',
                                               'reports/stock_checks'=>'Lot Reports',
                                               'weight_checks/weight_checks' => 'Weight Checks',
                                               'stock_summary_reports/overall_rolling_reports' => 'Overall Rolling Reports',
                                               'reports/daily_stock_reports' => 'Daily Stock Reports'
                                               ),
*/
		      'Stock Summary Reports' => array('stock_summary_reports/stock_summary_reports' => 'Stock Summary Report',
      					               'processes/process_masters' => 'Stock Report',
                       ),
                      'Receipt Department' => array('receipt_departments/receipt_departments'      => 'Metal Receipt',
                                                    /* 'daily_drawers/daily_drawer_receipts'         => 'Daily Drawer Receipt',
                                                     'receipt_departments/chain_receipts'          => 'Chain Receipt',
                                                     'receipt_departments/stone_receipts'          => 'Stone Receipt',
                                                     'receipt_departments/pending_ghiss_receipts'          => 'Pending Ghiss Receipt',
                                                     'receipt_departments/finished_goods_receipts' => 'Finished Goods Receipt',
                                                     'alloys/alloy_receipts'                       => 'Alloy Receipt','receipt_departments/rhodium_receipts'                       => 'Rhodium Receipt',
                                                     'receipt_departments/loss_receipts'          => 'Loss Receipt',
                                                     'receipt_departments/hallmark_receipts'          => 'Hallmark Receipt',
                                                   */  
                                                     ),
                      //'Parent Lots' =>'melting_lots/parent_lots',
                      'Melting Lots' => array('melting_lots/melting_lots' => 'Melting Lots',
                                              'melting_lots/parent_lots' => 'Parent Lots',
                                              ),
                                   
                      //'Product Rolling' => 'stock_summary_reports/product_rollings',
                       'RND' => array('rnds/rnd_receipts' => 'Receipt',
                                     'rnds/rnd_issues' => 'Issue',
                                     'rnds/rnd_karigar_receipts' => 'Karigar Receipt',
                                     'rnds/rnd_karigar_issues' => 'Karigar Issue',
                                     'rnds/rnd_karigar_reports' => 'Karigar Wise Report',
                                     'issue_and_receipts/rnd_ledgers' => 'Rnd Ledger',
                                     'rnds/rnd_list' => 'Rnd List',
                                     ),
                      'Export Internal' => array('export_internals/export_internal_receipts' => 'Receipt',
                                     'export_internals/export_internal_issues' => 'Issue',
                                     // 'rnds/rnd_karigar_receipts' => 'Karigar Receipt',
                                     // 'rnds/rnd_karigar_issues' => 'Karigar Issue',
                                     // 'rnds/rnd_karigar_reports' => 'Karigar Wise Report',
                                     // 'issue_and_receipts/rnd_ledgers' => 'Rnd Ledger',
                                     // 'rnds/rnd_list' => 'Rnd List',
                                     ),
                      'Domestic Internal' => array(
                                     'domestic_internals/domestic_internal_receipts' => 'Receipt',
                                     'domestic_internals/approval_processes' => 'Approval Process',
                                     'domestic_internals/hold_processes' => 'Hold Process',
                                     'domestic_internals/qc_processes' => 'Qc Process',
                                     'domestic_internals/gpc_processes' => 'GPC Process',
                                     ),
                      'Rope Chain' => array('rope_chains/melting_processes' => 'Melting Process',
                                            'rope_chains/machine_processes' => 'Machine Process',
                                            'rope_chains/final_processes' => 'Final Process',
                                            ),

                      'Choco Chain' => array(
                            //'choco_chains/combine_processes' => 'Combine Process',
                            'choco_chains/ags' => 'AG',
                            'choco_chains/machine_processes' => 'Chain Making',
                            // 'choco_chains/hand_cutting_processes' => 'Hand Cutting',
                             'choco_chains/final_processes' => 'GPC Final Process',
                            // 'choco_chains/imp_final_processes' => 'GPC Imp Final Process',
                            // 'choco_chains/rnd_processes' => 'GPC RND Process',
                            // 'choco_chains/quality_processes' => 'Quality Process',
                            // 'choco_chains/casting_final_processes' => 'GPC Casting Process',
                            // //'choco_chains/casting_seventy_final_processes' => 'Casting 75 Process',
                            //'choco_chains/casting_ninety_final_processes' => 'Casting 92 Process',

                            // 'choco_chains/melting_lot_reports' => 'Melting Lot Analysis',
                            // 'choco_chains/choco_chain_dye_processes' => 'Dye Process',
                            // 'choco_chains/choco_chain_dye_final_processes' => 'Dye Final Process',
                            // 'choco_chains/internal_gpc_processes' => 'Internal GPC Processes',

                            // 'choco_chains/choco_chain_cutting_pipes' => 'Cutting Pipe',
                            // 'choco_chains/choco_chain_solid_pipes' => 'Solid Pipes',
                            // 'choco_chains/choco_chain_hollow_pipes' => 'Hollow Pipes',
                            // 'choco_chains/choco_chain_solid_wires' => 'Solid Wires',
                            // 'choco_chains/choco_chain_hard_wires' => 'Hard Wires',

                        ),
   
                
                      'Solid Rope Chain' => array('solid_rope_chains/meltings' => 'Melting',
                                            'solid_rope_chains/machine_processes' => 'Machine Process',
                                            'solid_rope_chains/final_processes' => 'Final Process',
                                            'solid_rope_chains/final_gpc_processes' => 'GPC Process',
                                            'solid_rope_chains/melting_lot_reports' => 'Melting Lot Analysis',

                                            'solid_rope_chains/cutting_pipes' => 'Cutting Pipe',
                                                'solid_rope_chains/solid_pipes' => 'Solid Pipes',
                                                'solid_rope_chains/hollow_pipes' => 'Hollow Pipes',
                                                'solid_rope_chains/solid_wires' => 'Solid Wires',
                                                'solid_rope_chains/hard_wires' => 'Hard Wires',
                                            ),

                      'Solid Nawabi Chain' => array('solid_nawabi_chains/meltings' => 'Melting',
                                            'solid_nawabi_chains/chain_making_processes' => 'Chain Making Process',
                                            'solid_nawabi_chains/final_processes' => 'Final Process',
                                            ),

                      'Arc Order' => array('arc_orders/orders' => 'Digital Catalog Orders', //Orders
                                            // 'arc_orders/order_syncs' => 'Order Sync',
                                            'arc_orders/export_orders' => 'Export Orders',
                                            'arc_orders/swarnshilp_orders' => 'Swarnshilp Orders',
                                            'arc_orders/reject_orders' => 'Rejected Orders',
                                            'arc_orders/generate_lots' => 'Generate Lot',
                                            'arc_orders/wax_processes' => 'Wax Process',
                                            'arc_orders/wax_setting_processes' => 'Wax Setting Process',
                                            'arc_orders/project_processes' => 'Project Process',
                                            'arc_orders/investments' => 'Investments',
                                            'arc_orders/order_melting_lots' => 'Order Melting Lot'),
                        'Casting' => array(
                              'casting_processes/meltings' => 'Melting',
                             // 'casting_processes/harding_processes' => 'Harding',
                              'casting_processes/casting_processes' => 'Casting',
                              'casting_processes/filing_processes' => 'Filing',
                              'casting_processes/polish_processes' => 'Polish',
                              'casting_processes/stone_setting_processes' => 'Stone Setting',
                              'casting_processes/final_processes' => 'Final',
                        ),
                      'Wax Tree Process' =>array('wax_tree_process/wax_tree_processes'=>'Wax Tree Process','wax_tree_process/wax_tree_lot_no_processes'=>'Wax Tree Lot No Process'),
                      // 'Hallmarking' =>array(
                      //   'hallmarking/hallmark_receipt_processes'=>'Receipt',
                      //   'hallmarking/hallmark_out_processes'=>'Hallmark Out Process',
                      //   'hallmarking/hallmark_out_hold_processes'=>'Hallmark Out Hold Process',
                      //   'hallmarking/quality_manager_processes'=>'Quality Process',
                      //   'hallmarking/xrf_processes'=>'XRF Process',
                      //   'hallmarking/fire_assay_processes'=>'Fire Assay Process',
                      //   'hallmarking/huid_processes'=>'HUID Process',
                      //   'hallmarking/factory_out_processes'=>'Factory Out Process',
                      //   'hallmarking/fire_assay_out_chains'=>'Fire Assay Out Chain',
                      //   'hallmarking/fire_assay_out_reports'=>'Fire Assay Out Report',
                      // ),
                      'Factory Order'=>array( 'ka_chains/ka_chain_factory_order_masters'                        => 'Factory Order Masters',
                                          'ka_chains/ka_chain_factory_orders'                        => 'Factory Orders',
                                          'ka_chains/ka_chain_bunch_orders'                        => 'Bunch Orders',
                                          'ka_chains/ka_chain_factory_pending_orders'                        => 'Pending Orders',
                                          'ka_chains/ka_chain_bunch_pending_orders'                        => 'Bunch Pending Orders'),
                                          // 'ka_chains/ka_chain_factory_in_production_orders'                        => 'In Production Orders',
                                          // 'ka_chains/ka_chain_factory_ready_orders'                        => 'Ready Orders',),

                
                       'Office Outside' => array('office_outside/kdms' => 'KDM',
                                                'office_outside/final_processes' => 'Final Process',
                                                ),
                       'Daily Drawers' => array('daily_drawers/karigar_wise_daily_drawers' => 'DD Karigar Summary',
                                              ),
                       'Stone Issue' => array('stones/stone_issues'=>'Stone Issue',
                                             'stones/stone_issue_departments'=>'Factory To Karigar',
                                             'stones/stone_karigar_issue_departments'=>'Karigar To Factory',
                                             'stones/karigar_wise_stones'=>'Karigar Wise Stone Reports'),
                      /*'Chain Issue' => 'chains/chain_issues',
                      
                      'Metal Issue' => 'metals/metal_issues',*/
                      
                      'Nano Process' => 'nano_processes/nano_processes',
                      //'I 10 Process' => 'i_ten_processes/i_ten_processes',
                      // 'Dhoom A' => 'dhoom_a_processes/dhoom_a_processes',
                      // 'Dhoom B' => 'dhoom_b_processes/dhoom_b_processes',
                    
      'Daily Drawer Melting Process' => array(
      'daily_drawer_melting_processes/daily_drawer_melting_processes' => 'Daily Drawer Melting Process',
      'daily_drawer_melting_processes/daily_drawer_melting_final_processes' => 'Daily Drawer Melting Final Process'),
      'Issue Department' => array('issue_departments/issue_departments'=> 'Issue Department'),
      // 'GPC Powder Issue' => 'issue_departments/gpc_powder_issues',
      // 'Finish Goods' => 'issue_departments/finish_goods',
      'HCL' => array('hcl/hcl_wastages' => 'Wastages',
               'hcl/hcl_processes' => 'Process',
               'hcl/hcl_melting_processes' => 'HCL Melting Process',
               'hcl/hcl_process_balance' => 'HCL Process Balance',
               'hcl/hcl_wastage_balance' => 'HCL Wastage Balance',
               'hcl/hcl_lot_wise_reports' => 'HCL Wastage report',
               'issue_and_receipts/hcl_loss_ledgers' => 'HCL Loss Ledger'),

      'Pipe And Para Processes' => array(
          'pipe_and_para_processes/pipe_and_para_start_processes'                => 'Start Process',
          'pipe_and_para_processes/pipe_and_para_hold_processes'                 => 'Hold Process',
          'pipe_and_para_processes/pipe_and_para_copper_processes'               => 'Copper Process',
          'pipe_and_para_processes/pipe_and_para_cnc_processes'                  => 'CNC Process',
          'pipe_and_para_processes/pipe_and_para_dull_processes'                 => 'Dull Process',
          'pipe_and_para_processes/pipe_and_para_sand_dull_processes'                 => 'Sand Dull Process',
          'pipe_and_para_processes/pipe_and_para_lasiya_cutting_processes'                 => 'Lusiya Cutting Process',
          'pipe_and_para_processes/pipe_and_para_copper_dull_processes'          => 'Copper Dull Process',
          'pipe_and_para_processes/pipe_and_para_hand_cutting_processes'         => 'Hand Cutting Process',
          'pipe_and_para_processes/pipe_and_para_hand_cutting_ii_processes'         => 'Hand Cutting II Process',
          'pipe_and_para_processes/pipe_and_para_hand_cutting_iii_processes'         => 'Hand Cutting III Process',
          'pipe_and_para_processes/pipe_and_para_rhodium_processes'              => 'Rhodium Process',
          'pipe_and_para_processes/pipe_and_para_round_and_ball_chain_processes' => 'Round and Ball Chain Process',
          'pipe_and_para_processes/pipe_and_para_stripping_processes'                => 'Stripping Process',
          'pipe_and_para_processes/pipe_and_para_three_mm_slash_processes'                => '3.25 MM Slash',
          'pipe_and_para_processes/pipe_and_para_three_mm_dot_processes'                => '3.25 MM Dot',
          'pipe_and_para_processes/pipe_and_para_two_mm_slash_processes'                => '2 MM Slash',
          'pipe_and_para_processes/pipe_and_para_final_processes'                => 'Final Process'
          ),
      // 'Qc Departments'=>'qc_departments/qc_departments',
      // 'Packets'=>'chitties/chitties',

      'DD Issue Department' => array('daily_drawers/daily_drawer_issue_departments' => 'Factory to Karigar',
                               'daily_drawers/daily_drawer_karigar_issue_departments' => 'Karigar to Factory'),
     /* 'Solder Wastage' => array('solder_wastage_outs/solder_wastage_out_processes' => 'Process',
                   'solder_wastage_outs/solder_wastage_out_melting_processes' => 'Melting Process',
                        ),

      'Tounch' => array('tounch_outs/tounch_reports'=>'Tounch Report',
                  'tounch_outs/fire_tounch_reports'=>'Fire Tounch Report',
                  'tounch_outs/tounch_out_processes' => 'Tounch Out',
                  'tounch_outs/tounch_out_melting_processes' => 'Melting Process',
                  // 'tounch_outs/fire_tounch_out_processes' => 'Fire Tounch Out',
                  // 'tounch_outs/fire_tounch_out_melting_processes' => 'Fire Melting Process',
                  'issue_and_receipts/tounch_loss_fine_ledgers' => 'Tounch Loss Fine Ledger'
                  ),
      'Ghiss' => array('ghiss_outs/ghiss_reports'=>'Ghiss Report',
                 'ghiss_outs/ghiss_out_processes' => 'Ghiss Out',
                 'ghiss_outs/tounch_ghiss_out_processes' => 'Tounch Process',
                 'ghiss_outs/ghiss_out_melting_processes' => 'Melting Process',
                 'ghiss_outs/ghiss_out_final_processes' => 'Final Process',
                 'pending_ghiss_outs/pending_ghiss_out_processes'=>'Pending Ghiss Out',
                 'pending_ghiss_outs/pending_ghiss_issue_processes'=>'Pending Ghiss Issue',
                 'issue_and_receipts/ghiss_ledgers' => 'Ghiss Ledger',
                 'issue_and_receipts/pending_ghiss_ledgers' => 'Pending Ghiss Ledger',
                 'issue_and_receipts/pending_ghiss_ledgers' => 'Pending Ghiss Ledger'),
      'Ghiss Ledger'=>array(
                 'issue_and_receipts/department_wise_ghiss_ledgers' => 'Department Wise Ghiss Ledger',
                 'issue_and_receipts/rope_ghiss_ledgers' => 'Rope Ghiss Ledger'),
      'Melting Wastage Refine' => array(
              'melting_wastage_refine_outs/melting_wastage_refine_out_processes' => 'Melting Wastage Refine Out',
              'melting_wastage_refine_outs/melting_wastage_refine_out_melting_processes' => 'Melting Process'),


      'Alloy Issue' => 'alloys/alloy_issues',

      'Rope Ghiss Out' => array('hcl_ghiss_outs/hcl_ghiss_wastages' => 'Wastages',
                          'hcl_ghiss_outs/hcl_ghiss_out_processes' => 'Rope Ghiss Out',
                          'hcl_ghiss_outs/hcl_ghiss_out_melting_processes' => 'Melting Process'),
      'Loss' => array(
                'loss_outs/loss_reports'=>'Loss Report',
                'loss_outs/product_wise_loss_reports'=>'Product Wise Loss Report',
                'loss_outs/loss_out_processes' => 'Loss Out',
                'loss_outs/pending_loss_outs' => 'Pending Loss Outs',
                'loss_outs/melting_loss_outs' => 'Melting Loss Outs',
                'loss_outs/loss_out_melting_processes' => 'Melting Process',
                'loss_outs/melting_loss_out_processes' => 'Melting Out Process',
                'issue_and_receipts/overall_loss_ledgers' => 'Overall Loss Ledger',
                'issue_and_receipts/loss_ledgers' => 'Department wise Loss Ledger'),
      'Stone Melting Process' => array(
                'stone_vatav_outs/stone_vatav_processes' => 'Stone Process',
                'stone_vatav_outs/stone_vatav_melting_processes' => 'Melting Process',
                ),
      'Delay Reports' =>array('reports/due_reports'=>'Delay Pending Report',
                        'reports/delay_report_karigars'=>'Delay Completed Report',
                        'reports/office_days'=>'Office Calendar'),
      'Packing slip' =>array('export_internals/packing_slips'=>'Packing Slip'),
    */  'Refresh' => array('refresh/refresh_departments' => 'Refresh Receipt',
                   'refresh/refresh_hold' => 'Refresh Hold',
                   'refresh/refresh' => 'Refresh Repairing',
                   'refresh/refresh_hand_cutting_processes' => 'Hand Cutting',
                   'refresh/refresh_hand_dull_processes' => 'Hand Dull',
                   'refresh/refresh_final_processes' => 'Refresh Final',
                   'refresh/internal_gpc_processes' => 'Internal GPC Process'),
      // 'Internal' => array('internals/internal_receipts'=>'Internal Receipt',
      //               'internals/internal_final_processes'=>'Final Process'),
      //
      /* 'QR Code' => 'qr_codes/qr_codes',
      'Yellow QR Code' => 'qr_codes/yellow_qr_codes',
      'Generate Lot QR Code' => array(
        'qr_codes/generate_lot_taggings'=>'Generate Lot Tagging',
        'qr_codes/generate_lot_qr_codes'=>'Generate Lot Qr Code'),
      'Catalog QR Code' => 'catalog_qr_codes/catalog_qr_codes',
      'Masters' => array('users/accounts' => 'Accounts',
                   'masters/chains'=>'Chains',
                   'masters/category_1'=>'Category 1',
                   'masters/category_2'=>'Category 2',
                   'masters/category_3'=>'Category 3',
                   'masters/category_4'=>'Category 4',
                   'masters/category_5'=>'Category 5',
                   'masters/category_6'=>'Category 6',
                   'masters/processes_name'=>'Processes Name',
                   'masters/item_code_masters'=>'Item Code Masters',
                   'masters/process_detail_fields'=>'Processes Detail Fields',
                   'masters/machine_masters'=>'Machine Master',
                   'masters/domestic_category_masters'=>'Domestic Categories',
                   'masters/wastage_masters'=>'Wastage Master',
                   'masters/alloy_element_details'=>'Alloy Element Details',
                   'masters/customer_abbreviations'=>'Customer Abbreviations',
                   'masters/colour_abbreviations'=>'Colour Abbreviations',
                   'masters/stock_abbreviations'=>'Stock Abbreviations',
                   'masters/investment_ratios'=>'Investment Ratio',
                   'wastages/wastage_masters'=>'Issue Department Wastages',
                   'masters/melting_processes'=>'Melting Processes',
                   'masters/rolling_delay_time_masters'=>'Rolling Delay Time Master'),

      'Lengths' => 'lengths/lengths',

      'GPC Powder Internals'=>'settings/gpc_powder_internals',
      'KCNS'=>'settings/kcns',
*/
'Settings' => array(
                  //'users/accounts' => 'Accounts',
                  'masters/machine_masters'=>'Machine Master',
                  'settings/karigars' => 'Karigar Master',
                  'settings/same_karigars' => 'Karigars',
                  'settings/karigar_rates' => 'Karigar rates',
                  'settings/loss_percentages' => 'Loss percentage',
                  'settings/loss_categories' => 'Loss Categories',
                  //'settings/product_wise_loss_categories' => 'Product Wise Loss Categories',
                  //'settings/out_weight_categories' => 'Out Weight Categories',
                  //'settings/daily_drawer_wastage_categories' => 'Daily Drawer Wastage Categories',
                 // 'settings/alloy_details' =>'Alloy Settings',
                 // 'settings/alloy_types'=>'Alloy Types',
                  'settings/chain_purities'=> 'Chain Purities',
                 // 'settings/issue_purities'=> 'Issue Purities',
                 // 'settings/categories'=> 'Categories',
                  //'settings/category_fours'=> 'Design Names',
                  //'settings/customers'=> 'Customers',
                  //'settings/rods' =>'Rods',
                  //'settings/workers' =>'Workers',
                  //'settings/rooms' =>'Rooms',
                  //'settings/accessories' =>'Accessories',
                  'settings/departments' =>'Departments',
                  //'settings/lengths' => 'Lengths',
                  //'settings/open_fields' =>'Open Fields',
                  'masters/processes_name'=>'Processes Name',
                  'masters/process_detail_fields'=>'Process Detail Fields',
                  'users/ip_addresses'=>'Ip Address',
                  //'settings/internal_wastages'=>'Internal Wastages',
                  //'settings/cities'=> 'City',
                  'settings/person_productions'=> 'Person Productions',
                  //'settings/monthly_targets'=> 'Monthly Targets',
                  ),
// 'GPC Out Hold Process' =>'gpc_outs/gpc_out_hold_processes',

'User Management' => array('users/users' => 'Users',
                         'users/user_roles' => 'User Roles',
                         'users/change_password' => 'Change Password')
);
  $database_backup_menu = array('Backup Database' => 'settings/mysqldump');
  $melting_room_menu = array('Processes' => array('departments/melting'=>'Melting Room'));
  if(HOST=='BACKUP ARGOLD' || HOST=='BACKUP ARF' || HOST=='BACKUP ARC') 
    $main_menu=array_merge($database_backup_menu,$main_menu);
  if(in_array('departments/melting', $_SESSION['controller_list'])){
    $this->load->view('navigation/application/sidebar', array('main_menu' => $melting_room_menu,
                                                            'menu_icons' => $menu_icons));
  }else{
    $this->load->view('navigation/application/sidebar', array('main_menu' => $main_menu,
                                                            'menu_icons' => $menu_icons));
  }
?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />
<style> .icon-orange {
    color: #00bcd4;
    font-size: 18px;
    min-width: 24px;
    text-align: center;
    transition: color 0.3s ease;

  }</style>